### ISSUE TITLE
Help regarding Network Module

### ISSUE THREAD

**Issue by AntasJain16** [AliAsadi/Android-MVVM-Architecture#1]
I copies your project as it is, same code, and files,gradle properties, but when i am running my App The Network module says : No Item where as when i rum your's it shows the list of movie.
Please help with it ASAP.
Note: I have just updated the gradle implementation versions to latest one's and all other code is exactly same, its till not working.

**Comment by AliAsadi** [comment]
There was an issue with the API, Updated.
